#server:
#  servlet:
#    context-path: /api

# Connection properties DB
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/ogdatabase
    username: postgres
    password: password
    pool-size: 30

logging:
  level:
#    root: info
    com.example.ogame: trace

# URL Swagger start - http://localhost:8080/swagger-ui.html