CREATE TABLE IF NOT EXISTS technology (

    TECH_ID UUID NOT NULL PRIMARY KEY,
    TECH_NAME VARCHAR (40) NOT NULL,
    LVL INTEGER NOT NULL,
    METAL INTEGER NOT NULL,
    CRISTAL INTEGER NOT NULL,
    DEUTERIUM INTEGER NOT NULL,
    BUILD_TIME VARCHAR (20) NOT NULL,
    NEXT_BUILD_TIME VARCHAR (20) NOT NULL,
    IS_ABLE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS research (

    RESEARCH_ID UUID NOT NULL PRIMARY KEY,
    ENERGY_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    LASER_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    ION_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    HYPERSPACE_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    PLASMA_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    COMBUSTION_DRIVE UUID NOT NULL REFERENCES technology(TECH_ID),
    IMPULSE_DRIVE UUID NOT NULL REFERENCES technology(TECH_ID),
    HYPERSPACE_DRIVE UUID NOT NULL REFERENCES technology(TECH_ID),
    ESPIONAGE_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    COMPUTER_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    ASTROPHYSICS UUID NOT NULL REFERENCES technology(TECH_ID),
    INTERGALACTIC_RESEARCH_NETWORK UUID NOT NULL REFERENCES technology(TECH_ID),
    GRAVITON_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    WEAPONS_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    SHIELDING_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID),
    ARMOR_TECHNOLOGY UUID NOT NULL REFERENCES technology(TECH_ID)
);

ALTER TABLE user_instance
ADD COLUMN research_id UUID
REFERENCES research(RESEARCH_ID),
ADD UNIQUE (RESEARCH_ID);
